"""country_abbr_unique_player_nationality

Revision ID: 1eeb3fb84d6f
Revises: fdea2ac66f63
Create Date: 2025-04-04 19:56:32.297041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '1eeb3fb84d6f'
down_revision: Union[str, None] = 'fdea2ac66f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competitionplayerstats',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('competition_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('season_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('player_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('stat_type_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['competition_id'], ['competition.fbref_id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.fbref_id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.year'], ),
    sa.ForeignKeyConstraint(['stat_type_id'], ['stattype.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_country_abbr'), 'country', ['abbr'], unique=True)
    op.drop_constraint('player_based_country_id_fkey', 'player', type_='foreignkey')
    op.alter_column('player', 'based_country_id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.create_foreign_key(None, 'player', 'country', ['based_country_id'], ['abbr'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='foreignkey')
    op.create_foreign_key('player_based_country_id_fkey', 'player', 'country', ['based_country_id'], ['id'])
    op.alter_column('player', 'based_country_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=True)
    op.drop_index(op.f('ix_country_abbr'), table_name='country')
    op.drop_table('competitionplayerstats')
    # ### end Alembic commands ###
