"""Competition Stat Type team and competition id changed to fbref id

Revision ID: 31501b0117d5
Revises: 079c90571ab3
Create Date: 2025-02-27 22:51:17.165895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31501b0117d5'
down_revision: Union[str, None] = '079c90571ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitionteamstats', sa.Column('competition_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint('competitionteamstats_team_id_fkey', 'competitionteamstats', type_='foreignkey')
    op.alter_column('competitionteamstats', 'team_id',
               existing_type=sa.UUID(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.drop_constraint('competitionteamstats_compeition_id_fkey', 'competitionteamstats', type_='foreignkey')
    op.create_foreign_key(None, 'competitionteamstats', 'competition', ['competition_id'], ['fbref_id'])
    op.create_foreign_key(None, 'competitionteamstats', 'team', ['team_id'], ['fbref_id'])
    op.drop_column('competitionteamstats', 'compeition_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitionteamstats', sa.Column('compeition_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'competitionteamstats', type_='foreignkey')
    op.drop_constraint(None, 'competitionteamstats', type_='foreignkey')
    op.create_foreign_key('competitionteamstats_compeition_id_fkey', 'competitionteamstats', 'competition', ['compeition_id'], ['id'])
    op.create_foreign_key('competitionteamstats_team_id_fkey', 'competitionteamstats', 'team', ['team_id'], ['id'])
    op.alter_column('competitionteamstats', 'team_id',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('competitionteamstats', 'competition_id')
    # ### end Alembic commands ###
