"""player_stats_team_id

Revision ID: 9f7aa40f3351
Revises: f9185457574c
Create Date: 2025-04-04 20:42:30.134447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9f7aa40f3351'
down_revision: Union[str, None] = 'f9185457574c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competitionplayerstats', sa.Column('team_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key(None, 'competitionplayerstats', 'team', ['team_id'], ['fbref_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'competitionplayerstats', type_='foreignkey')
    op.drop_column('competitionplayerstats', 'team_id')
    # ### end Alembic commands ###
