"""player_birth_year

Revision ID: f9185457574c
Revises: 1eeb3fb84d6f
Create Date: 2025-04-04 20:09:39.252723

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9185457574c'
down_revision: Union[str, None] = '1eeb3fb84d6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('birth_year', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'birth_year')
    # ### end Alembic commands ###
