"""logo and avatar url in team competition and player

Revision ID: fdea2ac66f63
Revises: 9c00d85e12e9
Create Date: 2025-04-04 09:35:17.961476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fdea2ac66f63'
down_revision: Union[str, None] = '9c00d85e12e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fbref_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('based_country_id', sa.Uuid(), nullable=True),
    sa.Column('player_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('avatar_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['based_country_id'], ['country.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_fbref_id'), 'player', ['fbref_id'], unique=True)
    op.add_column('competition', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('team', sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'logo_url')
    op.drop_column('competition', 'logo_url')
    op.drop_index(op.f('ix_player_fbref_id'), table_name='player')
    op.drop_table('player')
    # ### end Alembic commands ###
