/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as ClientsIndexImport } from './routes/clients/index'
import { Route as CompetitionsnameImport } from './routes/competitions/[name]'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ClientsIndexRoute = ClientsIndexImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRoute,
} as any)

const CompetitionsnameRoute = CompetitionsnameImport.update({
  id: '/competitions/[name]',
  path: '/competitions/[name]',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/competitions/[name]': {
      id: '/competitions/[name]'
      path: '/competitions/[name]'
      fullPath: '/competitions/[name]'
      preLoaderRoute: typeof CompetitionsnameImport
      parentRoute: typeof rootRoute
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/competitions/[name]': typeof CompetitionsnameRoute
  '/clients': typeof ClientsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/competitions/[name]': typeof CompetitionsnameRoute
  '/clients': typeof ClientsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/competitions/[name]': typeof CompetitionsnameRoute
  '/clients/': typeof ClientsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/competitions/[name]' | '/clients'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/competitions/[name]' | '/clients'
  id: '__root__' | '/' | '/about' | '/competitions/[name]' | '/clients/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CompetitionsnameRoute: typeof CompetitionsnameRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CompetitionsnameRoute: CompetitionsnameRoute,
  ClientsIndexRoute: ClientsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/competitions/[name]",
        "/clients/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/competitions/[name]": {
      "filePath": "competitions/[name].tsx"
    },
    "/clients/": {
      "filePath": "clients/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
